#if !defined(flat_table_h)
#define flat_table_h

/* generated by maketable_flat.py */

#include "table.h"

#define FLAT_RECTIFIED_WIDTH 146
#define FLAT_RECTIFIED_HEIGHT 146


/* total table size 21316 elements 170528 bytes */
extern TableInputCoord const sFlatTableInputCoords[FLAT_RECTIFIED_HEIGHT][FLAT_RECTIFIED_WIDTH];

#endif
