#if !defined(flat_table_h)
#define flat_table_h

/* generated by maketable_flat.py */

#include "table.h"

#define FLAT_RECTIFIED_WIDTH 192
#define FLAT_RECTIFIED_HEIGHT 96


/* total table size 18432 elements 147456 bytes */
extern TableInputCoord const sFlatTableInputCoords[FLAT_RECTIFIED_HEIGHT][FLAT_RECTIFIED_WIDTH];

#endif
