#if !defined(table_h)
#define table_h

/* generated by maketable.py */

#define SOURCE_WIDTH 640
#define SOURCE_HEIGHT 480
#define INPUT_LEFT 94
#define INPUT_TOP 172
#define INPUT_WIDTH 452
#define INPUT_HEIGHT 236
#define RECTIFIED_WIDTH 150
#define RECTIFIED_HEIGHT 78

typedef struct TableInputCoord {
  float sy;
  float sx;
} TableInputCoord;

/* total table size 11700 elements 93600 bytes */
extern TableInputCoord const sTableInputCoords[RECTIFIED_HEIGHT][RECTIFIED_WIDTH];

#endif
