#if !defined(table_h)
#define table_h

/* generated by maketable.py */

#define SOURCE_WIDTH 640
#define SOURCE_HEIGHT 480
#define INPUT_LEFT 50
#define INPUT_TOP 240
#define INPUT_WIDTH 540
#define INPUT_HEIGHT 180
#define RECTIFIED_WIDTH 180
#define RECTIFIED_HEIGHT 60

typedef struct TableInputCoord {
  float sy;
  float sx;
} TableInputCoord;

/* total table size 10800 elements 86400 bytes */
extern TableInputCoord const sTableInputCoords[RECTIFIED_HEIGHT][RECTIFIED_WIDTH];

#endif
